# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: jpegtran 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "jpegtran"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Martin Poljak"]
  s.date = "2015-08-15"
  s.email = "martin@poljak.cz"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "CHANGES.txt",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "jpegtran.gemspec",
    "lib/jpegtran.rb",
    "test",
    "test.jpg"
  ]
  s.homepage = "https://github.com/martinkozak/jpegtran"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Ruby interface to 'jpegtran' tool."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hash-utils>, [">= 0.18.0"])
      s.add_runtime_dependency(%q<command-builder>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<unix-whereis>, [">= 0.1.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
    else
      s.add_dependency(%q<hash-utils>, [">= 0.18.0"])
      s.add_dependency(%q<command-builder>, [">= 0.2.0"])
      s.add_dependency(%q<unix-whereis>, [">= 0.1.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    end
  else
    s.add_dependency(%q<hash-utils>, [">= 0.18.0"])
    s.add_dependency(%q<command-builder>, [">= 0.2.0"])
    s.add_dependency(%q<unix-whereis>, [">= 0.1.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
  end
end

